allowBuilds:
  puppeteer: false

minimumReleaseAgeExclude:
  - '@rsbuild/*'
  - '@rslib/*'
  - '@rslint/*'
  - '@rspack/*'
  - '@rspress/*'
  - '@rstackjs/*'
  - '@rstest/*'
  - 'rsbuild-plugin-*'
  - rstack
